# DEFINE NAMESPACE
apiVersion: v1
kind: Namespace
metadata:
  name: pod-namespace # set namespace name

---

# DEFINE POD
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-app  # set pod label "app"
  name: pod-app-v1  # set pod name
  namespace: pod-namespace  # set namespace

spec:
  terminationGracePeriodSeconds: 60 # set termination period
  containers:
  - name: app-v1-container # set container name
    image: acrani/application/test-app-v1:0.0.1 # set image name
    ports:  # expose pod port and set port name
    - containerPort: 3000
      name: pod-port
    env: 
      - name: ENV_VAR
        value: REPLACE_ENV_VAR


  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true

---

# DEFINE SERVICE 
apiVersion: v1
kind: Service
metadata:
  name: pod-service # set service name
  namespace: pod-namespace  # set namespace

spec:
  selector:
    app: pod-app  # selector target pod with label app = pod-app

  type: ClusterIP # set service as ClusterIP

  ports:
  - name: service-port  # set service port name
    protocol: TCP # allow only TCP flow
    port: 3000 # set port number
    targetPort: pod-port # service-port targets pod-port

#NOTE: as were are using a ClusterIP Service, the pod, service and cluster ports must be the same number. 
# Other wise any connection will be refused.     